### ISSUE TITLE
can i change the star to other picture?

### ISSUE THREAD

**Issue by heiyeliuying** [DreaminginCodeZH/MaterialRatingBar#1]
can i change the star to other picture?

**Comment by zhanghai** [comment]
You can (in a kinda hacky way), but I wouldn't recommend doing so, because it is against the Material Design guidelines and I didn't intend to support other designs during implementation.

You can do so via the resource-overriding trick, by placing a resource with the same name as the one that a library uses, and it will replace the library one during the build process. To be specific, you can place `mrb_star_border_icon_black_36dp.xml` and `mrb_star_icon_black_36dp.xml` in your `res` directory and it will replace the stars.

**Comment by heiyeliuying** [comment]
@DreaminginCodeZH thanks a lot

**Comment by Qw4z1** [comment]
It would be nice to have the option to use completely filled stars when using them as indicators. Compare with Google Play where bordered stars are used where the user can interact with the rating bar and filled stars are used where the user can't.

**Comment by zhanghai** [comment]
@Qw4z1 Maybe you can use the appcompat version in this case

**Comment by devabir93** [comment]
i replace the icons but it didn't work for me.

**Comment by ghost** [comment]
mrb_star_border_icon_black_36dp.xml and mrb_star_icon_black_36dp.xml 
Do I need to create those files for every api / screen density like in your library?
In your library files are xml and png. Which ones do I need?
Just placing 2 xml files in res/drawable doesn't work.

**Comment by devabir93** [comment]
yes, I added a vector and add "override = true" and it works.

**Comment by ghost** [comment]
@devabir93 placed override="true" into vector tag and it doesn't work :/

**Comment by shubham696** [comment]
@zhanghai  I added both icons in res/drawable
but it's not working.
@heiyeliuying  @devabir93 can you help me with this

**Comment by ghost** [comment]
@shubham696 
I switched to regular RatingBar.
Just set this in RatingBar's attributes in xml:
`android:progressDrawable="@drawable/rating_stars"`

and put this in drawables:

```
<?xml version = "1.0" encoding ="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item
        android:id="@android:id/background"
        android:drawable="@drawable/star_50" />
    <item
        android:id="@android:id/secondaryProgress"
        android:drawable="@drawable/star_50" />
    <item
        android:id="@android:id/progress"
        android:drawable="@drawable/star_100" />
</layer-list>
```

star_50 means 50% opacity of a star drawable

**Comment by shubham696** [comment]
> @shubham696
> I switched to regular RatingBar.
> Just set this in RatingBar's attributes in xml:
> `android:progressDrawable="@drawable/rating_stars"`
> 
> and put this in drawables:
> 
> ```
> <?xml version = "1.0" encoding ="utf-8"?>
> <layer-list xmlns:android="http://schemas.android.com/apk/res/android">
>     <item
>         android:id="@android:id/background"
>         android:drawable="@drawable/star_50" />
>     <item
>         android:id="@android:id/secondaryProgress"
>         android:drawable="@drawable/star_50" />
>     <item
>         android:id="@android:id/progress"
>         android:drawable="@drawable/star_100" />
> </layer-list>
> ```
> 
> star_50 means 50% opacity of a star drawable

@s7aycool Thank you for the reply. But regular rating bar doesn't support the match parent attribute.
Due to this I have to use this one only

**Comment by devabir93** [comment]
> @zhanghai I added both icons in res/drawable but it's not working. @heiyeliuying @devabir93 can you help me with this

you need to put the new icons in drawable-anydpi-v21 and it will work
