### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by jgn89** [DreaminginCodeZH/MaterialRatingBar#10]
How do you call the onchangelistener?

**Comment by zhanghai** [comment]
Don't know what you are asking -- "You can call the listener manually with `OnRatingChangeListener.onRatingChanged()`" answers your question literally, but I don't think you are asking what you intended to know.

You might be interested in [How To Ask Questions The Smart Way](http://www.catb.org/esr/faqs/smart-questions.html).

**Comment by jordyamc** [comment]
Its possible to set the Rating bar to only call onRatingChanged() only when the user stop scrolling and not calling every time including when calling setRating()??

**Comment by zhanghai** [comment]
@jordyamc Yes, you can use [RatingBar.setOnRatingBarChangeListener()](https://developer.android.com/reference/android/widget/RatingBar.html#setOnRatingBarChangeListener(android.widget.RatingBar.OnRatingBarChangeListener)) if you only want to be notified when user releases the touch. The library added another listener just as an alternative like the one in Seekbar. You can get whether the callback is from user with its parameter fromUser.
