### ISSUE TITLE
Change star color in onRatingChanged

### ISSUE THREAD

**Issue by matthewkrueger** [DreaminginCodeZH/MaterialRatingBar#11]
I'd like to change the color of all the stars as the rating value changes.  I have ranges where a rating of [0-1] is red, (1-3) is yellow and [3-5] is green.

I added an OnRatingChangeListener to my class, but I can't figure out the proper way to set the color for the stars.  Can you provide a specific example for how to programmatically change the fill color of the stars?  

I think it has to do with the tint color, but I couldn't find good documentation to explain this.  Thanks in advance!

**Comment by zhanghai** [comment]
You can do what can be done with the framework `RatingBar` tinting (`setProgressTintList()` etc), and it is automatically backported by this library.

If you are not familiar with widget tinting in Android, please consult Android documentation, Google or StackOverflow first.

**Comment by matthewkrueger** [comment]
Thanks for the help.  This is what ended up working for me:

Implement an OnRatingChangeListener.  In the onRatingChanged method, do this:

```
LayerDrawable stars = (LayerDrawable) ratingBar.getProgressDrawable();
stars.getDrawable(2).setColorFilter(getBackgroundColorForRating(ratingBar.getContext(), rating), PorterDuff.Mode.SRC_ATOP);
stars.getDrawable(1).setColorFilter(getBackgroundColorForRating(ratingBar.getContext(), rating), PorterDuff.Mode.SRC_ATOP);
```
   
Where ```getBackgroundColorForRating``` returns the proper color for the rating you're displaying.

**Comment by zhanghai** [comment]
I believe calling ratingBar.setProgressTintList(), setSecondaryProgressTintList() and setProgressBackgroundTintList() respectively with your color is a more reasonable implementation. Your approach assumed the internal implementatuon of this library, which is subject to change without notice.

**Comment by matthewkrueger** [comment]
There is no ```setProgressTint()``` method that I can find.

I'm not familiar with how to create a ColorStateList programmatically, which I believe is required to use the other methods you mentioned.  Do you know how that works or where to look?  I agree my implementation is not great, but it was suggested several places on the internet, and works right now.  Suggestions and help much appreciated.

Great library!

**Comment by zhanghai** [comment]
Sorry I am on my phone and incorrectly assumed the existence of the tint color versions of the methods (which Drawables have). I've corrected them now.

For creating a ColorStateList from color, use ColotStateList.valueOf().

**Comment by matthewkrueger** [comment]
Thank you for the help!  Here's my updated calls (I left the backgroundTintList alone so that when the star isn't filled in, it uses the default colors):

```
ratingBar.setProgressTintList(ColorStateList.valueOf(getBackgroundColorForRating(rating)));
ratingBar.setSecondaryProgressTintList(ColorStateList.valueOf(getBackgroundColorForRating(rating)));
```

**Comment by zhanghai** [comment]
LGTM. You can also reuse the ColorStateList, because they are the same and ColorStateList is immutable.
