### ISSUE TITLE
MaterialRatingBar is not working in MI Devices

### ISSUE THREAD

**Issue by karthickperumal** [DreaminginCodeZH/MaterialRatingBar#12]
I am using material rating bar in my application everything is working in all android devices except Redmi 3s prime (MIUI).Star is not looks like material rating bar. Kindly provide me a solution asap.

**Comment by zhanghai** [comment]
What is the look on MIUI devices? (e.g. You can attach a screenshot)

What have you done in solving this issue? (e.g. Locating the source of problem, suspected causes)

I don't have a MIUI device, so if you want to solve it quickly, you could provide some more specific information.

**Comment by karthickperumal** [comment]
@DreaminginCodeZH I found whats the issue is, think so. I just upgraded my support library version from 24 to 25 its resolved.
Thanks for your quick response.
