### ISSUE TITLE
Changing star color for API level < 21

### ISSUE THREAD

**Issue by lucasharada** [DreaminginCodeZH/MaterialRatingBar#17]
How can I change the star colors on XML file? 

I made it work with `<item name="android:progressTint">@color/ratingbarColor</item>`, but Android Studio warns me about this not working for devices with API level below 21.

**Comment by zhanghai** [comment]
From README.md:

> 8 tint-related attributes such as app:mrb_progressTint and app:mrb_progressTintMode are also supported so that they can control the tinting of rating drawables. The default tint color is ?colorControlActivated, and the default tint mode is src_in.
