### ISSUE TITLE
only as view. no edit mode

### ISSUE THREAD

**Issue by softmarshmallow** [DreaminginCodeZH/MaterialRatingBar#21]
is it possible to use this as just viewing the rating?
not interactable.

**Comment by zhanghai** [comment]
Use `style="@style/Widget.MaterialRatingBar.RatingBar.Indicator"` or `style="@style/Widget.MaterialRatingBar.RatingBar.Indicator.Small"`.

**Comment by softmarshmallow** [comment]
thanks!
