### ISSUE TITLE
mrb_secondaryProgressTint  color issue

### ISSUE THREAD

**Issue by ChetnaNakum** [DreaminginCodeZH/MaterialRatingBar#27]
I have set color in mrb_secondaryProgressTint but it does not apply.I want to apply empty star color.But how can apply empty(Non-progress) star color? (Now, It looks transparent. I want to apply color in empty star)

**Comment by zhanghai** [comment]
From README:

> You can use `app:mrb_fillBackgroundStars` to control whether background stars are filled, otherwise it defaults to the same value as android:isIndicator which is the behavior of Google apps.

**Comment by ChetnaNakum** [comment]
I use:


        <me.zhanghai.android.materialratingbar.MaterialRatingBar
            style="@style/Widget.MaterialRatingBar.RatingBar.Indicator"
            android:layout_width="@dimen/item_search_result_rating_mar_w"
            android:layout_height="@dimen/item_search_result_rating_mar_h"
            android:layout_marginLeft="15dp"
            android:minHeight="@dimen/item_search_result_rating_mar_h"
            android:minWidth="@dimen/item_search_result_rating_mar_w"
            android:numStars="5"
            app:mrb_fillBackgroundStars="true"
            android:isIndicator="false"
            app:mrb_progressTint="@color/star_fill_color"
            app:mrb_secondaryProgressTint="@color/star_empty_color" />

**Still It disappear empty star.I want filled empty star with color.**

**Comment by zhanghai** [comment]
Sorry this is a bug. Fixed and released in [v1.2.0](https://github.com/DreaminginCodeZH/MaterialRatingBar/releases/tag/v1.2.0).

**Comment by goodlifechris** [comment]
android:progressBackgroundTint="@color/colorDarkBlue"
Thank me later
