### ISSUE TITLE
如果不添加app:mrb_progressTint等参数,运行结果为空白

### ISSUE THREAD

**Issue by zsyh** [DreaminginCodeZH/MaterialRatingBar#3]
如果不添加app:mrb_progressTint和app:mrb_progressBackgroundTint,运行结果为空白，我还以为是没有成功导入库，或者这个库本身存在问题，其实只是没有显示出来。
If you can't understand Chinese, I'll rewrite it in English.

**Comment by zhanghai** [comment]
Tint defaults to ?colorControlActivated as stated in README, so that most people can automatically get the correct color. If you don't want to use appcompat, you'll need to set these tints to your own custom values.

**Comment by zsyh** [comment]
thanks
