### ISSUE TITLE
Tinting the border

### ISSUE THREAD

**Issue by Dragas** [DreaminginCodeZH/MaterialRatingBar#32]
Yo! How do you tint the non-filled stars? I found that you use png drawables but they come up as white ones instead of black. Do you default some tinting mode?

**Comment by zhanghai** [comment]
Hi Dragas

You can tint them with `app:mrb_progressTint`, `app:mrb_secondaryProgressTint` and `app:mrb_progressBackgroundTint`, which are backported versions of standard `ProgressBar` tint attributes.
