### ISSUE TITLE
how to  make the ratingBar read-only

### ISSUE THREAD

**Issue by adustdu2015** [DreaminginCodeZH/MaterialRatingBar#34]
using the component can  be  remarked.how to make it a certain value,cannot remark,thanks

**Comment by zhanghai** [comment]
Cannot fully understand your issue, but if you are asking how to make it read-only, use the Indicator style, or manually set `android:isIndecator` to `true`.

**Comment by adustdu2015** [comment]
thank  you . i  just want to know  "how to make it read-only", my English is so bad . thank you again.
