### ISSUE TITLE
Tinting border and isIndicator not working properly

### ISSUE THREAD

**Issue by Hiike** [DreaminginCodeZH/MaterialRatingBar#36]
I need to have the stars yellow and the user can't change the rating.
So I used the properties : 
```
@color/yellow = #fae22f
app:mrb_progressTint="@color/yellow"
app:mrb_progressBackgroundTint="@color/yellow"
app:mrb_secondaryProgressTint="@color/yellow"
android:isIndicator="true"
android:numStars="5"
android:rating=3.5"
```

Should have 3.5 stars filled with yellow and 1.5 stars with only the border colored, but with isIndicator, every stars are filled.

So I used this instead
```
RatingBar ratingBar = (RatingBar)findViewById(R.id.ratingBar);
ratingBar.setOnTouchListener(new OnTouchListener() {
        public boolean onTouch(View v, MotionEvent event) {
            return true;
        }
    });
```
Do you plan to fix this ?

**Comment by zhanghai** [comment]
You set `app:mrb_progressBackgroundTint="@color/yellow"`, and when `android:isIndicator="true"`, the default style has a light transparent grey **filled** star progress background, similar to what we can see in Play Store. So with your tint it ended up tinted to opaque yellow.

If you don't want to fill the background stars, add `app:mrb_fillBackgroundStars="false"`. Alternatively you can tint the background stars with a lighter yellow.

**Comment by Hiike** [comment]
Thank you for your help !
`app:mrb_fillBackgroundStars="false"` did the thing.
