### ISSUE TITLE
Setting the clickable does not work. I tried to fix it this way.

### ISSUE THREAD

**Issue by wangyea** [DreaminginCodeZH/MaterialRatingBar#38]
is that right?
@Override
    public boolean onTouchEvent(MotionEvent event) {
     
       //add this  
        if (!isClickable()) {
            return false;
        }
        if (isIndicator()) {
            return false;
        }
        float eventX = event.getX();
        float eventY = event.getY();
        switch (event.getAction()) {
            case MotionEvent.ACTION_DOWN:
                mStartX = eventX;
                mStartY = eventY;
                mPreviousRating = mRating;
                break;
            case MotionEvent.ACTION_MOVE:
                if (!isScrollable()) {
                    return false;
                }

                handleMoveEvent(eventX);
                break;
            case MotionEvent.ACTION_UP:
                if (!RatingBarUtils.isClickEvent(mStartX, mStartY, event) || !isClickable()) {
                    return false;
                }

                handleClickEvent(eventX);
        }
 
        getParent().requestDisallowInterceptTouchEvent(true);
        return true;
    }

**Comment by zhanghai** [comment]
What are you trying to do?
