### ISSUE TITLE
Not working with Jetifier

### ISSUE THREAD

**Issue by ghost** [DreaminginCodeZH/MaterialRatingBar#39]
Unable to resolve dependency for ':app@quality_assuranceDebug/compileClasspath': Failed to transform file 'library-1.2.0.aar' to match attributes {artifactType=jetified-aar} using transform JetifyTransform

When trying to refactor to androidX, whenever i remove this library, everything works fine.

**Comment by zhanghai** [comment]
Never used JetifyTransform. Is there any additional information?

**Comment by rubengees** [comment]
@DreaminginCodeZH I also have this problem. This happens because the current `aar` has two `AndroidManifest` files for some reason. Would be great to have a release with a new aar.

```bash
$ unzip -d test library-release.aar
Archive:  library-release.aar
  inflating: test/AndroidManifest.xml  
  inflating: test/proguard.txt       
  inflating: test/R.txt              
replace test/AndroidManifest.xml? [y]es, [n]o, [A]ll, [N]one, [r]ename: r
new name: AndroidManifest2.xml
  inflating: test/AndroidManifest2.xml  
  inflating: test/classes.jar  
  ...

$ ls test
aidl                  AndroidManifest.xml  classes.jar  libs          res
AndroidManifest2.xml  assets               jni          proguard.txt  R.txt
```

**Comment by zhanghai** [comment]
New release [v1.3.1](https://github.com/DreaminginCodeZH/MaterialRatingBar/releases/tag/v1.3.1) ~~should be available on maven central within several hours~~ is available now.
