### ISSUE TITLE
setRating 

### ISSUE THREAD

**Issue by ghost** [DreaminginCodeZH/MaterialRatingBar#40]
How can I use setRating set the value is 8.9 or 6.8 and so on ,like  this picture 
![image](https://user-images.githubusercontent.com/35981460/40266361-5c830568-5b7c-11e8-9302-992e050dd814.png)
my  code is :
![image](https://user-images.githubusercontent.com/35981460/40266387-cf7ba17e-5b7c-11e8-88e3-4dbd853064c4.png)

the result is:
![image](https://user-images.githubusercontent.com/35981460/40266396-ef5ed1f0-5b7c-11e8-91dc-90d4faa1f810.png)

Thank you

**Comment by zhanghai** [comment]
You need `android:stepSize` or `RatingBar.setStepSize()`.

**Comment by ghost** [comment]
@DreaminginCodeZH 
![image](https://user-images.githubusercontent.com/35981460/40286877-63c316d6-5cdc-11e8-9067-eef0ff0711b5.png)
I haved set android:stepSize=0.1 but do not work
![image](https://user-images.githubusercontent.com/35981460/40286934-be1ab44a-5cdc-11e8-9809-872f92b25fe6.png)

**Comment by zhanghai** [comment]
You can refer to the decimal step size section of the demo app; though your configuration seems correct to me.

**Comment by kokobebekoko** [comment]
i have this question too

**Comment by kelalaka153** [comment]
I've a similar issue. I've found that android:isIndicator="true" is the problem. Making it false solves the problem but this time editable..
