### ISSUE TITLE
Click MaterialRatingBar with isIndicator attribute

### ISSUE THREAD

**Issue by EduardoDornel** [DreaminginCodeZH/MaterialRatingBar#44]
I have a XML: `<me.zhanghai.android.materialratingbar.MaterialRatingBar
                                android:id="@+id/ratingBar"
                                android:layout_width="0dp"
                                android:layout_weight="8"
                                android:layout_height="wrap_content"
                                android:rating="0"
                                android:layout_gravity="center"
                                android:isIndicator="true"
                                app:mrb_progressTint="@color/yellow_stars"
                                app:mrb_progressBackgroundTint="@color/divider_gray"
                                style="@style/Widget.MaterialRatingBar.RatingBar" />`

and in my Java code i set clickListener method, but it's never called. If i remove `isIndicator` attribute, this works

**Comment by zhanghai** [comment]
Working as intended. Indicator `RatingBar`s are by definition read-only so listeners won't be fired.

If you have more questions, please confirm that it is not a framework behavior (like this one) by checking whether it happens with a regular framework `RatingBar`.
