### ISSUE TITLE
All com.android.support libraries must use the exact same version specification

### ISSUE THREAD

**Issue by yigitserin** [DreaminginCodeZH/MaterialRatingBar#46]
I am getting this error on my gradle file after updating to build tools 28.

**Comment by zhanghai** [comment]
You can specify the version of support library you want to use in your gradle file by explicitly adding `implementation 'com.android.support:<MODULE>:28.0.0'`. The next update will be AndroidX (when ButterKnife 9.0.0 is out) so currently I don't plan to release it with just a dependency change anyway.

**Comment by zhanghai** [comment]
Done.
