### ISSUE TITLE
Dynamic Star Count

### ISSUE THREAD

**Issue by touhiDroid** [DreaminginCodeZH/MaterialRatingBar#48]
Does the library support dynamic star count, i.e. 3/6/10 stars instead of 5 as per the dynamic need of the user? 

I have not found any such option given & even easily manageable in the code. If there is no such feature, what is the right way to implement it?

**Comment by zhanghai** [comment]
The library didn't mention it because it's already a feature from the framework `RatingBar` . Check out `android:numStars` and `setNumStars(int)`.
