### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by bzjlj** [DreaminginCodeZH/MaterialRatingBar#51]
isIndicator设为true时
如果设置了mrb_secondaryProgressTint属性
当rating=2.5会显示3个星星

**Comment by zhanghai** [comment]
> The secondary progress should not be modified by the client as it is used internally as the background for a fractionally filled star.
> https://developer.android.com/reference/android/widget/RatingBar

Secondary progress is always filled to ceiled value. If you don't want this behavior, don't use secondary progress. So this looks like a framework behavior, not a bug in this library.
