### ISSUE TITLE
What's the difference between rating bar and rating bar indicator?

### ISSUE THREAD

**Issue by ZiranLi** [DreaminginCodeZH/MaterialRatingBar#52]
Thanks for your great work! Once more thing is, what's the difference between 
**style="@style/Widget.MaterialRatingBar.RatingBar.Indicator.Small**  and **style="@style/Widget.MaterialRatingBar.RatingBar.Small"** ? I just want to make sure that I've used the correct one. 
Thanks!

**Comment by zhanghai** [comment]
The concept of indicator is not something added by this library, so you can check out the [framwork documentation about RatingBar](https://developer.android.com/reference/android/widget/RatingBar). Just Ctrl-F for "Indicator" and there's several places related to this style.

**Comment by ZiranLi** [comment]
Ok I get it now. Thank you very much.
