### ISSUE TITLE
I wonder if it is possible to remove empty star border altogether? also is it possible to change colour of empty stars ? (to match the border)

### ISSUE THREAD

**Issue by bastami82** [DreaminginCodeZH/MaterialRatingBar#54]
something like Normal layout : Framework Implementation (first rating type in the attached image) ?
I tried this but no luck : 
  ```
    app:mrb_progressBackgroundTint="@color/colorGrey"
    app:mrb_indeterminateTint="@color/colorGrey"
    app:mrb_secondaryProgressTint="@color/colorGrey"
```

![sample_app](https://user-images.githubusercontent.com/15080319/50043476-ca2e2300-006c-11e9-9e40-0a56da0e55a9.jpg)

**Comment by zhanghai** [comment]
For your purpose you can just use the AppCompat RatingBar.

**Comment by bastami82** [comment]
It seems I did not explain my question well, I quite like the `match parent` option in MaterialRatingBar however I wonder if we can customise the progress icons. change them to something else completely or at least change empty stars shape i.e without border ?  (I know we can customise the color of filled ones with `app:mrb_progressTint` and colour of secondary progress with `app:mrb_secondaryProgressTint` but what if we just want the empty state in solid color (without border)? I might be wrong but  AppCompat RatingBar  `match parent`  does not work as expected same as normal RatingBar.

**Comment by zhanghai** [comment]
See #1.
