### ISSUE TITLE
Unfilled

### ISSUE THREAD

**Issue by yecaler** [DreaminginCodeZH/MaterialRatingBar#57]
![image](https://user-images.githubusercontent.com/25024969/53380617-fb01d100-39a8-11e9-8435-163fcb595de6.png)

**Comment by zhanghai** [comment]
The label says "framework implementation", and it's meant to show one of the reasons to use this library instead 😅

**Comment by yecaler** [comment]
What should I do?

**Comment by zhanghai** [comment]
Use this library. That one is framework `RatingBar`, and using `MaterialRatingBar` from this library fixes it.

**Comment by yecaler** [comment]
Well, thank you
