### ISSUE TITLE
When isIndicator="true" no more floating values

### ISSUE THREAD

**Issue by kelalaka153** [DreaminginCodeZH/MaterialRatingBar#58]
When isIndicator="false" I can get floating values correctly, half filled stars, etc. However, when I set the isIndicator="true" floating values are converted into integers. 

Is this a bug or a feature? I need indicator so that user can't feel that he can change the star value.

**Comment by zhanghai** [comment]
Cannot reproduce. In the sample app, the "Decimal step size" section has the isIndicator="true" and floating point values, animated as well. You can check out the layout XML of the sample app for reference.
