### ISSUE TITLE
Fill Stars Background if isIndicator=true

### ISSUE THREAD

**Issue by feriousa** [DreaminginCodeZH/MaterialRatingBar#60]
Hi, default value for fillBackgroundStars is 'isIndicator' value and must be changed to false.

In MaterialRatingBar.java, line 101

`boolean fillBackgroundStars = a.getBoolean(
                R.styleable.MaterialRatingBar_mrb_fillBackgroundStars, isIndicator());`

**Comment by zhanghai** [comment]
Can you elaborate on why it **must** be changed to `false`?

**Comment by fr2ad** [comment]
Because if i set `isIndicator` to `true`, it fill the star's background.

**Comment by zhanghai** [comment]
What about setting `app:mrb_fillBackgroundStars="false"` on the `MaterialRatingBar` in layout XML?

**Comment by fr2ad** [comment]
This is a workaround and i used it, but the `fillBackgroundStars` default value should not get from `isIndicator`

**Comment by zhanghai** [comment]
This is the intended usage and fillBackgroundStars defaulting from isIndicator is working as intended, unless there is a strong reason that the current behavior is wrong.
