### ISSUE TITLE
MaterialRatingBar中心是空心的问题

### ISSUE THREAD

**Issue by zzh1026** [DreaminginCodeZH/MaterialRatingBar#7]
大神您好,原生的RatingBar位选中的star中心可以填充, 但是使用MaterialRatingBar后star中心是空心的,并且不能修改,未选中的星星需要是实心全白的,但是只能改变star边缘的颜色是怎么回事??? 还有请问原生的RatingBar点击状态为啥外围又一层类似于光圈的东西? 我用的是sdk23

**Comment by zhanghai** [comment]
空心是设计问题——我认为（以及 Google 的应用也采用了）空心的设计更加符合 Material Design，而框架提供的不够美观/符合规范。
参考项目 README 可以看到改变不同状态星星颜色的方式。
如果你想采用的不是 Material Design，可能需要考虑使用其他库。

**Comment by zzh1026** [comment]
谢谢您的回答,我知道了

**Comment by zhanghai** [comment]
已实现并发布： https://github.com/DreaminginCodeZH/MaterialRatingBar/releases/tag/v1.1.1
