### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.

### ISSUE THREAD

**Issue by mavris** [DreaminginCodeZH/MaterialRatingBar#70]
I am currently using v1.3.2
and I tried to update to
`implementation 'me.zhanghai.android.materialratingbar:library:1.4.0'` but the Android won't build and will show this error:
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
When I point it to v1.3.3  everything seems to work fine.
Any ideas?

**Comment by zhanghai** [comment]
I don't have an idea. This library is just an aar, and an error like that is usually emitted by gradle plugins.
