### ISSUE TITLE
Question about setOnRatingChangeListener

### ISSUE THREAD

**Issue by malikbilal1997** [DreaminginCodeZH/MaterialRatingBar#73]
Is there any way to make the ```setOnRatingChangeListener``` to be called when when user _**Stop Dragging the MaterialRatingBar**_. Normally it works fine for me except when user drag the MaterialRatingBar. Actually i'm using it with ```Firebase``` so it keep updating while user dragging the MaterialRatingBar. Thanks

**Comment by zhanghai** [comment]
You can just use [`RatingBar.setOnRatingBarChangeListener()`](https://developer.android.com/reference/android/widget/RatingBar#setOnRatingBarChangeListener(android.widget.RatingBar.OnRatingBarChangeListener)), which only notifies the listener when dragging finishes. `MaterialRatingBar.setOnRatingChangeListener()` was added by me as another alternative for developers who do need to listen to changes while dragging, e.g. update some descriptive text accordingly.
