### ISSUE TITLE
half star is not showing correctly when isIndicator is true

### ISSUE THREAD

**Issue by YLPeng** [DreaminginCodeZH/MaterialRatingBar#74]
It seems the rating stars are nor showing correctly when isIndicator set to true
for example, when I set rating to 4.5 it shows 5 starts instead of 4.5 stars

**Comment by zhanghai** [comment]
Did you set `andriod:stepSize="0.1"`?

**Comment by YLPeng** [comment]
thanks for the timely response, yes I did tried setting `setSize="0.1"` as you suggested but the issue still occurs.
![image](https://user-images.githubusercontent.com/15114149/94094801-3eb2fb80-fdd5-11ea-8633-8e51d2532ea4.png)
above screenshot is when `isIndicator=true` and `stepSize=0.1`

when setting `isIndicator=false` the star is showing correctly:
![image](https://user-images.githubusercontent.com/15114149/94094873-715cf400-fdd5-11ea-8992-fb817f7ef850.png)
the score is 4.8 but the actual rating is floored down to 4.5

**Comment by zhanghai** [comment]
Can you try to reproduce it with the sample app? It has this exact case working properly for me.

**Comment by YLPeng** [comment]
yes the sample app works fine. after setting `app:mrb_fillBackgroundStars="true"` it's working, I guess the problem was background color and tint color are the same before so it always shows 5 stars. Thanks.
