### ISSUE TITLE
how to disable the ontouch event ? 

### ISSUE THREAD

**Issue by taouichaimaa** [DreaminginCodeZH/MaterialRatingBar#77]
I don't want the user to change the stars on touch or on click . How can I disable user input ?

**Comment by zhanghai** [comment]
This is a general question for Android `RatingBar` so please search or ask in a difference place. But you can also just look at the source code of the sample app in this project.

**Comment by AndroidDeveloperLB** [comment]
I think this should answer it:

https://developer.android.com/reference/android/widget/RatingBar#attr_android:isIndicator
