### ISSUE TITLE
OnRatingBarChangeListener is not raised!

### ISSUE THREAD

**Issue by etymontechnologies** [DreaminginCodeZH/MaterialRatingBar#9]
When I set rating to 6, [MaterialRatingBar](https://github.com/DreaminginCodeZH/MaterialRatingBar) does not raise **OnRatingChangeListener**!!

```xml
<me.zhanghai.android.materialratingbar.MaterialRatingBar
        android:id="@+id/ratingBar"
        android:layout_width="260dp"
        android:layout_height="24dp"
        android:numStars="10"
        android:rating="6"
        android:stepSize="1"
        />
```

```java
MaterialRatingBar ratingBar = (MaterialRatingBar) findViewById(R.id.ratingBar);
ratingBar.setOnRatingChangeListener(new MaterialRatingBar.OnRatingChangeListener() {
            @Override
            public void onRatingChanged(MaterialRatingBar ratingBar, float rating) {
                Log.d("Test", String.format(Locale.US, "Rating: %f", rating));
            }
        });
ratingBar.setRating(6);
```

**Comment by zhanghai** [comment]
This is working as intended, the same as framework `ProgressBar` -- Setting the same value again won't trigger listeners, as `setRating()` will call [`setProgressInternal()` which simply returns after the check](https://github.com/android/platform_frameworks_base/blob/0d2a46b7336b6d255f202b878003be59ecbae52b/core/java/android/widget/ProgressBar.java#L1441).
